version: '3.9'

services:
  backend:
    container_name: betterbike_backend
    image: betterbike_backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/betterbike?schema=public
  db:
    container_name: betterbike_db
    image: postgres:13.3-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=betterbike
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
